### ISSUE TITLE
sftp.stat(file).mtime is broken/outdated

### ISSUE THREAD

**Issue by 4ndyfix** [spider-gazelle/ssh2.cr#20]
Hi,
it throws an exception:
lib/ssh2/src/sftp/attributes:63:10
63 | Time.epoch(@stat.mtime.to_i32)
Error: undefined method 'epoch' for Time.class

**Comment by stakach** [comment]
fixed in 7f78b60f20d2a117aa736b806a597d23737888b9
cut a new release with that fix too
