### ISSUE TITLE
Agent login does not work for me

### ISSUE THREAD

**Issue by djmaze** [spider-gazelle/ssh2.cr#4]
I tried with different servers using `login_with_agent`. It always fails with the following error on my machine:

```
Unhandled exception: Failed to authenticate username root with SSH agent (SSH2::SSH2Error)
  from lib/ssh2/src/agent.cr:0:5 in 'authenticate'
  from lib/ssh2/src/session.cr:122:7 in 'login_with_agent'
```

(Arch Linux, openssh 8.1p1-1, Crystal 0.31.1)

**Comment by djmaze** [comment]
I added some error handling so the message now reads

```
Unhandled exception: Failed to authenticate username root with SSH agent, error code -37, Would block (SSH2::SSH2Error)
```

**Comment by djmaze** [comment]
Well, i just added a `@session.perform_nonblock do` block around the `LibSSH2.agent_userauth` call, and I am able to login. 

(Disclaimer: I don't really know what I am doing there.)

**Comment by stakach** [comment]
Yeah I haven't used agent auth for any of my programmatic SSH usage.
I was actually going to caution you on using agent auth as I am not sure how the C-Lib implements the comms and it might block the crystal reactor.

But it seems `perform_nonblock` is the solution to that.

**Comment by djmaze** [comment]
Okay, I will try using this for a while. I can create a PR if it turns out to be working reliably.

**Comment by stakach** [comment]
That would be awesome! Thanks!

**Comment by djmaze** [comment]
Seems to be working well.
