### ISSUE TITLE
Add binding for `libssh2_userauth_keyboard_interactive_ex`

### ISSUE THREAD

**Issue by kimburgess** [spider-gazelle/ssh2.cr#8]
There does not currently appear to be a binding for [`libssh2_userauth_keyboard_interactive_ex`](https://www.libssh2.org/libssh2_userauth_keyboard_interactive_ex.html). This would be useful / required for establishing connections where `userauth_password` is unsupported.

**Comment by stakach** [comment]
annoyingly the method in libssh2 would request input from STDIN which is not desirable (especially since we're using that for core -> driver comms)

So need to think of another way of supporting that...

**Comment by stakach** [comment]
Actually I'm wrong, it does support a password callback.

**Comment by stakach** [comment]
fix by https://github.com/spider-gazelle/ssh2.cr/commit/0ea54780b1adfa867f4367785771e06b36afe731

Spec written but doesn't work with the test container as I had to manually enable interactive auth... Will work something out.
